"""passportaosrusages -> passportusages

Revision ID: 07e0b2ef4761
Revises: 314bab3318ad
Create Date: 2025-03-18 13:08:00.484037

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07e0b2ef4761'
down_revision: Union[str, None] = '314bab3318ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('passportusages',
    sa.Column('aosr_material_id', sa.Integer(), nullable=False),
    sa.Column('passport_id', sa.Integer(), nullable=False),
    sa.Column('used_volume', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['aosr_material_id'], ['aosrmaterials.id'], ),
    sa.ForeignKeyConstraint(['passport_id'], ['passports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('passportaosrusages')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('passportaosrusages',
    sa.Column('passport_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('used_volume', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('aosr_material_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['aosr_material_id'], ['aosrmaterials.id'], name='passportaosrusages_aosr_material_id_fkey'),
    sa.ForeignKeyConstraint(['passport_id'], ['passports.id'], name='passportaosrusages_passport_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='passportaosrusages_pkey')
    )
    op.drop_table('passportusages')
    # ### end Alembic commands ###
