"""added units and volumes

Revision ID: 0d900884644c
Revises: 29914b84c083
Create Date: 2025-01-13 13:19:17.509009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d900884644c'
down_revision: Union[str, None] = '29914b84c083'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('aosrmaterial', sa.Column('volume', sa.Integer(), nullable=False))
    op.add_column('material', sa.Column('units', sa.String(), nullable=False))
    op.add_column('sectionmaterial', sa.Column('volume', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sectionmaterial', 'volume')
    op.drop_column('material', 'units')
    op.drop_column('aosrmaterial', 'volume')
    # ### end Alembic commands ###
