"""materials.density -> passports.density

Revision ID: 128c6cc92e99
Revises: a98a718ffb10
Create Date: 2025-04-15 10:31:35.012403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '128c6cc92e99'
down_revision: Union[str, None] = 'a98a718ffb10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('materials', 'density')
    op.add_column('passports', sa.Column('density', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('passports', 'density')
    op.add_column('materials', sa.Column('density', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text("'1'::double precision"), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
