"""added density to materials

Revision ID: 14e942a41ec3
Revises: 07e0b2ef4761
Create Date: 2025-03-25 12:36:27.493150

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "14e942a41ec3"
down_revision: Union[str, None] = "07e0b2ef4761"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "materials",
        sa.Column("density", sa.Float(), nullable=False, server_default="1"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("materials", "density")
    # ### end Alembic commands ###
