"""Deleted unused indexes from tables

Revision ID: 1669e160da5d
Revises: 1cda8224347e
Create Date: 2025-03-03 08:21:47.456645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1669e160da5d'
down_revision: Union[str, None] = '1cda8224347e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_aosrmaterials_aosr_id', table_name='aosrmaterials')
    op.drop_index('ix_aosrmaterials_material_id', table_name='aosrmaterials')
    op.drop_index('ix_aosrs_section_id', table_name='aosrs')
    op.drop_index('ix_projectmaterials_material_id', table_name='projectmaterials')
    op.drop_index('ix_projectmaterials_project_id', table_name='projectmaterials')
    op.drop_index('ix_sectionmaterials_material_id', table_name='sectionmaterials')
    op.drop_index('ix_sectionmaterials_section_id', table_name='sectionmaterials')
    op.drop_index('ix_sections_project_id', table_name='sections')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_sections_project_id', 'sections', ['project_id'], unique=False)
    op.create_index('ix_sectionmaterials_section_id', 'sectionmaterials', ['section_id'], unique=False)
    op.create_index('ix_sectionmaterials_material_id', 'sectionmaterials', ['material_id'], unique=False)
    op.create_index('ix_projectmaterials_project_id', 'projectmaterials', ['project_id'], unique=False)
    op.create_index('ix_projectmaterials_material_id', 'projectmaterials', ['material_id'], unique=False)
    op.create_index('ix_aosrs_section_id', 'aosrs', ['section_id'], unique=False)
    op.create_index('ix_aosrmaterials_material_id', 'aosrmaterials', ['material_id'], unique=False)
    op.create_index('ix_aosrmaterials_aosr_id', 'aosrmaterials', ['aosr_id'], unique=False)
    # ### end Alembic commands ###
