"""fixed aosr -> aosr_material in passport usages

Revision ID: 3e9e1766f4df
Revises: 9007fd9ca1d3
Create Date: 2025-03-14 11:48:03.677725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e9e1766f4df'
down_revision: Union[str, None] = '9007fd9ca1d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
