"""Disable unique values for aosr_name

Revision ID: 445639b4bab2
Revises: 0d900884644c
Create Date: 2025-01-22 09:44:58.742329

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '445639b4bab2'
down_revision: Union[str, None] = '0d900884644c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('aosr_aosr_name_key', 'aosr', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('aosr_aosr_name_key', 'aosr', ['aosr_name'])
    # ### end Alembic commands ###
