"""AosrMaterial.section_material_id=SectionMaterial.material_id -> SectionMaterial.id

Revision ID: 4d2d93f51e8b
Revises: 7dd204f51a5b
Create Date: 2025-04-04 10:07:49.399180

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d2d93f51e8b'
down_revision: Union[str, None] = '7dd204f51a5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('aosrmaterials_section_material_id_fkey', 'aosrmaterials', type_='foreignkey')
    op.create_foreign_key(None, 'aosrmaterials', 'sectionmaterials', ['section_material_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'aosrmaterials', type_='foreignkey')
    op.create_foreign_key('aosrmaterials_section_material_id_fkey', 'aosrmaterials', 'sectionmaterials', ['section_material_id'], ['material_id'])
    # ### end Alembic commands ###
