"""FOREIGN KEY AosrMaterial.section_material_id - uniqueis off


Revision ID: 5e6425859329
Revises: dde3953643c0
Create Date: 2025-04-10 12:10:27.007151

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e6425859329'
down_revision: Union[str, None] = 'dde3953643c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('aosrmaterials_section_material_id_key', 'aosrmaterials', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('aosrmaterials_section_material_id_key', 'aosrmaterials', ['section_material_id'])
    # ### end Alembic commands ###
