"""Fix for previous migration

Revision ID: 791f98201254
Revises: 2a8977599baf
Create Date: 2025-04-02 08:08:40.497100

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "791f98201254"
down_revision: Union[str, None] = "2a8977599baf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("aosrmaterials", sa.Column("section_material_id", sa.Integer()))
    op.create_unique_constraint(None, "aosrmaterials", ["section_material_id"])
    op.create_unique_constraint(None, "sectionmaterials", ["id"])
    op.create_foreign_key(
        None,
        "aosrmaterials",
        "sectionmaterials",
        ["section_material_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "sectionmaterials", type_="unique")
    op.drop_constraint(None, "aosrmaterials", type_="foreignkey")
    op.create_foreign_key(
        "aosrmaterials_section_material_id_fkey",
        "aosrmaterials",
        "sectionmaterials",
        ["section_material_id"],
        ["id"],
    )
    op.drop_constraint(None, "aosrmaterials", type_="unique")
    op.drop_column("aosrmaterials", "section_material_id")
    # ### end Alembic commands ###
