"""fixed many-to-many relationship

Revision ID: 9007fd9ca1d3
Revises: 3962ebb75319
Create Date: 2025-03-14 11:44:59.644838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9007fd9ca1d3'
down_revision: Union[str, None] = '3962ebb75319'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('passportaosrusages', sa.Column('aosr_material_id', sa.Integer(), nullable=False))
    op.drop_constraint('passportaosrusages_aosr_id_fkey', 'passportaosrusages', type_='foreignkey')
    op.create_foreign_key(None, 'passportaosrusages', 'aosrmaterials', ['aosr_material_id'], ['id'])
    op.drop_column('passportaosrusages', 'aosr_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('passportaosrusages', sa.Column('aosr_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'passportaosrusages', type_='foreignkey')
    op.create_foreign_key('passportaosrusages_aosr_id_fkey', 'passportaosrusages', 'aosrs', ['aosr_id'], ['id'])
    op.drop_column('passportaosrusages', 'aosr_material_id')
    # ### end Alembic commands ###
