"""added many-to-many relationship for aosr_materials and passports

Revision ID: c0027d02889c
Revises: 829eb44aaa04
Create Date: 2025-03-14 08:48:37.071042

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0027d02889c'
down_revision: Union[str, None] = '829eb44aaa04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('passportaosrusages',
    sa.Column('aosr_id', sa.Integer(), nullable=False),
    sa.Column('passport_id', sa.Integer(), nullable=False),
    sa.Column('used_volume', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['aosr_id'], ['aosrs.id'], ),
    sa.ForeignKeyConstraint(['passport_id'], ['passports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('passportaosrusages')
    # ### end Alembic commands ###
