"""Added cascade delete for section_material

Revision ID: dde3953643c0
Revises: 1cbb47a7b9f3
Create Date: 2025-04-07 07:31:08.684744

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dde3953643c0'
down_revision: Union[str, None] = '1cbb47a7b9f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
